language: python
python:
  - "2.7"
env:
  matrix:
      - DRF_VERSRION=">=2.0,<2.1"
      - DRF_VERSRION=">=2.1,<2.2"
      - DRF_VERSRION=">=2.2,<2.3"
      - DRF_VERSRION=">=2.3,<2.4"
      - DJANGO_VERSION=">=1.4,<1.5"
      - DJANGO_VERSION=">=1.5,<1.6"
      - OSCAR="django-oscar>=0.5,<0.6"
      - OSCAR="git@github.com:tangentlabs/django-oscar#egg=django-oscar-dev"
install:
  - pip install Django$DJANGO_VERSION djangorestframework$DRF_VERSION $OSCAR
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
script:
  - py.test tests --pep8 --cov fancypages
after_success:
  - coveralls
